### ISSUE TITLE
add option to 'keep material slots' to the texture atlasser [enhancement]

### ISSUE THREAD

**Issue by SupraLP** [michaeldegroot/cats-blender-plugin#100]
[enhancement]
i'm mostly using the same shader on my models wich means, that i could use the same material on everything, but.... sometimes i want to change something individually afterwards in unity. Therefore it would be nice if I could just atlas everything and still have the option to change the shader or texture of parts of the model afterwards.

**Comment by Darkblader24** [comment]
That's now possible, thanks!
