### ISSUE TITLE
Addon won't enable

### ISSUE THREAD

**Issue by Snipkitty** [michaeldegroot/cats-blender-plugin#101]
I was having no problems at all with Cats, up until about 3 months ago. The old version wouldn't connect to google to do bone translations, so i swapped to the newer version. Now the newer version refuses to enable and keeps giving messages like this. Any idea whats causing this?
![20190208_155437](https://user-images.githubusercontent.com/47465335/52512569-5286fb00-2bba-11e9-9d40-d22aa8484e71.jpg)

**Comment by Darkblader24** [comment]
Can you try it again with the development version of cats?

**Comment by Darkblader24** [comment]
I will close this for now. If the issue still occurs, please reopen this.
