### ISSUE TITLE
Concern about cache ripping protection

### ISSUE THREAD

**Issue by Primpri** [michaeldegroot/cats-blender-plugin#102]
I don't mean to be rude, but what kind of "cache ripping" is the "cache ripping protection" supposed to protect against? From what I understand, all it's doing is deforming the mesh on a basis blendshape, and hoping that the ripped model does not include blendshapes? But when would it not? From GPU caching? I suppose a malformed FBX conversion could cause it too.

I tried this using one of my own models and built a tool to extract my model from VRChat's web cache (which are literally just asset bundle files with web header, not even encrypted). Using the FBX conversion library, I was able to re-import my model back into Blender with no issue fixing the basis with mixing.

It's a thoughtful attempt, but I don't think you should be suggesting that this "protection" can actually protect anything with 100% guarantee, it's nothing more than a small inconvenience to someone who understands how to mix blendshapes -  though I'd imagine most people stealing models have very little experience with Blender so it may protect against most theft attempts.

The only way we're going to get proper ripping protection is if VRChat implements encryption, though even then it'll always be possible to rip.

**Comment by Darkblader24** [comment]
That is very true, it is not a 100% protection, but it's the best we can do. I will reword it a bit to make it sound less ripping proof

**Comment by Darkblader24** [comment]
Ok, I made it pretty clear now that it is not a 100% protection. Thanks for the suggestion!

**Comment by avail** [comment]
When a model with ripping protection gets ripped and imported into unity, the 'basis original' shape key is missing from the ripped version, so all you get is a model that looks like the beginning of this gif https://i.imgur.com/RlrGTvV.gif
