### ISSUE TITLE
CATS v0.12.2 Join Selected Meshes joins All

### ISSUE THREAD

**Issue by 000TragicSolitude** [michaeldegroot/cats-blender-plugin#104]
On separating meshes of a model I want to use, and specifically selecting some meshes on the model, pressing "Selected" on the _Join Meshes_ options joins "All" instead.
Naming doesn't seem to be the issue, as even if I have the main body mesh named that, everything still gets rejoined. I'm also not seeing any errors pop-up what so ever.
Tested to see if it worked with CATS version 0.12.1, and it works as expected there, but not 0.12.2.

Also, small suggestion, can you add a function to the "Selected" option of _Join Meshes_ to preserve naming? Maybe through selecting a "master" mesh from a drop-down after the button is pressed, just to use for the sake of a name? May be a little nitpicky, sorry.

**Comment by Darkblader24** [comment]
That bug is fixed in the development version of cats.

And about the name preservation, that's a good idea. I will probably remove the renaming
