### ISSUE TITLE
I can not turn on the plugin

### ISSUE THREAD

**Issue by Romzik85** [michaeldegroot/cats-blender-plugin#106]
blender v2.80.44
launched as admin
![clipboarder 2019 02 17](https://user-images.githubusercontent.com/15080586/52909141-7f56a480-3283-11e9-9100-4d9f1ce0d51d.png)

**Comment by Cmyth01** [comment]
Happening here as well, tried in 2.79 and latest version of 2.8

**Comment by ppsmol** [comment]
Same in 2.8

**Comment by Pyroglyph** [comment]
This happens with the development version of the plugin too.

**Comment by LucidAPs** [comment]
This happens to me aswell in 2.79 and 2.8.

**Comment by edwios** [comment]
Same here, Blender 2.8 Mac

**Comment by avail** [comment]
try the development branch.

**Comment by Darkblader24** [comment]
Thanks for reporting, it's fixed now. Update to the latest cats development version with the build-in updater (dropdown cats in user preferences) and if you use 2.80, to the latest Blender 2.80 beta version (https://builder.blender.org/download/)
