### ISSUE TITLE
(Feature request) Separate mesh by shape key inclusion

### ISSUE THREAD

**Issue by theepicsnail** [michaeldegroot/cats-blender-plugin#107]
Separating meshes by whether a vertex is in any shape keys is helpful for knowing what you can/can't safely decimate. I've got this for selecting all the vertices that are moved by any shape keys on the mesh.

Should only need hooking it up to a button and doing the actual split by selected afterwards.

```python
import bpy
import bmesh

context = bpy.context
TOL = 1e-5 # tolerance
ob = context.edit_object
me = ob.data

bm = bmesh.from_edit_mesh(me)

for v in bm.verts:
    bv = me.vertices[v.index]
    for sk in me.shape_keys.key_blocks:
        if (sk.data[v.index].co - bv.co).length > TOL:
            v.select = True
            break # No need to check the rest of the shape keys

bmesh.update_edit_mesh(me)
```

Source/reference:
https://blender.stackexchange.com/questions/116764/select-vertices-which-are-affected-by-a-shape-key/116814

**Comment by Darkblader24** [comment]
Thanks, awesome idea. I will add this

**Comment by Darkblader24** [comment]
It is now added to the development version of cats. Give it a try!
