### ISSUE TITLE
Cats Plugin will not enable on blender 2.8 (Windows)

### ISSUE THREAD

**Issue by BigTurboTM** [michaeldegroot/cats-blender-plugin#109]
When I try to load Cats on Blender 2.8, I recieve the error listed in the screenshot below. I've attempted running Blender as an administrator, as well as trying both master and development branches. They both yield similar responses.

(Dev branch)
![Screenshot_8](https://user-images.githubusercontent.com/38849339/54723062-8e9b6d00-4b23-11e9-9d12-574490feaab4.jpg)

(Master branch)
![Screenshot_9](https://user-images.githubusercontent.com/38849339/54723162-e9cd5f80-4b23-11e9-9b3d-35cc0b694e43.jpg)

I did attempt simply restarting blender as other threads reported, and got a very different error, but an error nonetheless.
![Screenshot_10](https://user-images.githubusercontent.com/38849339/54723260-4e88ba00-4b24-11e9-93cb-bb3d8d87bf23.jpg)

The development branch after restarting however reports the same exact issue as before.

I do enjoy Blender 2.8's UI far more than I do Blender 2.79's. However, my becoming spoiled by Cats leaves me at the mercy of blender's beta's ironically less stable predecessor. Your plugin is absolutely fantastic and makes my workflow so much easier. I hope a fix to this issue can be found soon. Thank you for your time in reading this.

(20-Mar-2019)

**Comment by Darkblader24** [comment]
Thanks for reporting, it's fixed now. Update to the latest cats development version with the build-in updater (dropdown cats in user preferences)

**Comment by BigTurboTM** [comment]
Aye, thank you for your speedy work. It is running beautifully, now!
