### ISSUE TITLE
Blender 2.8 Error loading mmd_tools [Linux]

### ISSUE THREAD

**Issue by OneVoltTen** [michaeldegroot/cats-blender-plugin#110]
https://pastebin.com/raw/EUkwHV5N

ValueError: expected UIList, MMD_ROOT_UL_display_items class "draw_filter" function to have 3 args, found 4

**Comment by Darkblader24** [comment]
Thanks for the report! I'm aware of that but I have to wait for mmd_tools to fix this unfortunately.
