### ISSUE TITLE
Traceback error upon loading zip into blender

### ISSUE THREAD

**Issue by Echomocha** [michaeldegroot/cats-blender-plugin#111]
![](https://cdn.discordapp.com/attachments/361742235525709825/565111686940459009/unknown.png)

Got this error upon installing the 2.8 version of cats. Is there anything I can do personally or is this is coding issue? (new to everything, sorry)

**Comment by Darkblader24** [comment]
It's fixed in the development version of cats: https://github.com/michaeldegroot/cats-blender-plugin/archive/development.zip
