### ISSUE TITLE
Blender 2.8

### ISSUE THREAD

**Issue by wuyhas** [michaeldegroot/cats-blender-plugin#112]
is not working in blender 2.8, I cant enable it.

**Comment by wuyhas** [comment]
https://gyazo.com/1e8dfffe5e008bdeaa02ffda82fd39fe

**Comment by Darkblader24** [comment]
Use the development version of cats for Blender 2.8

**Comment by wuyhas** [comment]
it was my bad I had it installed in the 2.79 and it made conflicts and errors somehow
