### ISSUE TITLE
blender 2.8 cant turn on pugin version 1.12.2

### ISSUE THREAD

**Issue by captainfloofs** [michaeldegroot/cats-blender-plugin#113]
![image](https://user-images.githubusercontent.com/47815483/56537125-f6612f80-6589-11e9-800f-a898e4cff3cc.png)

**Comment by thiagokyo** [comment]
Same error here, i tried to change directory to the addons folder of the app, i renamed the folder without "-" and none spaces but the error persists.

**Comment by Darkblader24** [comment]
Only the dev version of cats works in Blender 2.80 currently. Install this: https://github.com/michaeldegroot/cats-blender-plugin/archive/development.zip
