### ISSUE TITLE
Blender 2.79: 0.13.1 causes mesh to become transparent inside and by defaults turns off importing models with bones auto-orienting.

### ISSUE THREAD

**Issue by Shararamosh** [michaeldegroot/cats-blender-plugin#119]
0.13.1 causes mesh to become transparent when you see it from the inside and also why importing model using CATS's import the auto-orientation of bones is turned off despite being turned on in 0.12.2.

**Comment by Darkblader24** [comment]
The mesh probably becomes transparent because backface culling is active. And I disabled auto orientation because I want to add my own orientation fix, but it was not ready yet.
Both issues will be fixed in the next update.
