### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by xXRyanPowellXx** [michaeldegroot/cats-blender-plugin#121]
I was watching a tutorial on YT of how to inport the add on to Blender. i clicked on the "user prefrances" and then "Install from file" i chose the "Cat" adon and i clicked "install from file" the next thing the person says on YT was "Make sure the box is ticked or it will or be activated" I was trying to click the tick but it didnt let me.. It came up with this big coding script..

**Comment by Darkblader24** [comment]
What error did you get?

**Comment by azurely27** [comment]
I have a same question. 
Error message is this.
"Traceback (most recent call last):Import Error cannot import name `globs'

**Comment by Darkblader24** [comment]
> I have a same question.
> Error message is this.
> "Traceback (most recent call last):Import Error cannot import name `globs'

That sounds like you are using an old cats version. Make sure you are using 0.13.2
