### ISSUE TITLE
[Feature Request] Add VRChat ready rig

### ISSUE THREAD

**Issue by cubedparadox** [michaeldegroot/cats-blender-plugin#122]
Not 100% sure if this makes sense to add to cats, but I'd love an option under the Add->Armature-> dropdown in the 3d viewport to spawn in a default unity/vrchat ready mesh. Currently I use the rigify metarig for this, but that rig comes with a bunch of extra bones that I have to delete, and I get warnings about bone angles when using it in VRChat. 

Probably a fairly small feature, but it'd be a nice timesave for people rigging models from scratch!

**Comment by Darkblader24** [comment]
Thats a great idea, I will add this to my todo list. Thanks 👍
