### ISSUE TITLE
[Bug] Join Mesh causes hard crash of blender

### ISSUE THREAD

**Issue by UiharuKazari2008** [michaeldegroot/cats-blender-plugin#123]
When working with my model and I try to merge my "02_Skin" mesh to "Beanie" it will cause blender to hard crash, no console message, just completely close. If I remove the vertex groups from the hat and merge it, its fine. So I feel like there's something its tripping up on with  the vertex groups but I can't identify what the real issue is as it just hard crashes. 

I have tried this on both my MBP, MB Air, and my Windows Gaming PC all running Blender 2.79b and they all crash. Only on Mac OS I get a actual the actualy crash report.

<img width="1257" alt="Screen Shot 2019-05-18 at 20 11 15" src="https://user-images.githubusercontent.com/15165770/57988439-60230b00-7a5c-11e9-81c7-e402680a5e6a.png">

Sometimes I also get this message when merging it but right now its just crashing every time I add something new
<img width="472" alt="Screen Shot 2019-05-18 at 02 13 21" src="https://user-images.githubusercontent.com/15165770/57988445-80eb6080-7a5c-11e9-80e8-2a74b59715c2.png">

If you need me to show you more I can show on Discord Kazari#2705

**Comment by UiharuKazari2008** [comment]
Update: I have fix the issue sort of, It looks like the vertex groups on that mesh had gotten corrupted or messed up where even using Clean in weight painting would cause a hard crash. I had to re-weight paint the head and all and now it looks to be fine. 

Don't know if CATS or Blender can catch this error instead of just hard crashing and leaving no trace or any information about the error

**Comment by Darkblader24** [comment]
There is not much that Cats can do in such a case unfortunately. Especially crashes are hard to deal with because the crash log not very informative about the issue.
