### ISSUE TITLE
Only Exports Directly to root directory not can't do folders.

### ISSUE THREAD

**Issue by Cariaga** [michaeldegroot/cats-blender-plugin#124]
i can only export on my D drive root
file imported from VRM, applied all the fixes that tool has

other bugs 
only exports ones and need to reset blender
image not embeded on export

current version 2.8 
plugin version 0.13.2

[Sendagaya_Shino.zip](https://github.com/michaeldegroot/cats-blender-plugin/files/3207673/Sendagaya_Shino.zip)

**Comment by Darkblader24** [comment]
The exporting process is done by Blender, not by Cats. Maybe try starting Blender as admin to allow export to other drives. 
Regarding the other issue, try importing the textures into Unity first before importing the fbx.
