### ISSUE TITLE
Fix Model bug

### ISSUE THREAD

**Issue by VexMex** [michaeldegroot/cats-blender-plugin#125]
I have a strange bug that when i import a model (.fbx file directly from the unity folder) and then click on "fix Model", The mesh gets completly seperated from the bones and turned 180° for whatever reason. And i have no clue on how to recombine all the bones into the right place

I hope this is a bug? if you want to try it for yourself
Blender 2.79b from steam
your plugin v 0.13.2
Aeon Liazrard from Vrcmods website

**Comment by Darkblader24** [comment]
I'm not sure what causes this, but you can just rotate the armature and mesh back in place using the transforms in the menu which appears by pressing N: https://i.imgur.com/fGUdh5w.png

After you are done rotating them back, just press Apply Transforms in Cats: https://i.imgur.com/togCoTH.png
