### ISSUE TITLE
Lights normals inverted when full body tracking fix 

### ISSUE THREAD

**Issue by wiliunamed** [michaeldegroot/cats-blender-plugin#129]
![Anotación 2019-05-27 140242](https://user-images.githubusercontent.com/51083190/58418556-54e96400-8088-11e9-9825-86fe28eb6816.png)

the light directions and normal maps are working weird in many shaders when full body tracking fix is used.

**Comment by Darkblader24** [comment]
THe fbt fix only moves a few bones around, so it don't make sense that normals would be effected by it. Are you sure that you didn't change anything else?

**Comment by wiliunamed** [comment]
I simply mark this option and that happens, but if it's not active it works well
![Anotación 2019-05-29 154351](https://user-images.githubusercontent.com/51083190/58562062-c6f8af00-8228-11e9-93c1-6aea6ae1a4cd.png)
