### ISSUE TITLE
Request: Button to reset shape keys to 0

### ISSUE THREAD

**Issue by Erumite** [michaeldegroot/cats-blender-plugin#131]
When testing shape keys to figure out gestures, it's often a pain to scroll through all the shapes and reset them to 0.  I suggest a button under the model options menu to reset all shape keys to zero, and possibly select Basis to ensure that any edits after that point would be to the basis. 

Looks to be relatively simple: https://blender.stackexchange.com/questions/27872/how-to-set-a-specific-value-for-multiple-shape-keys

**Comment by Darkblader24** [comment]
You should give this little button a try: https://i.imgur.com/Ye9nSJ8.png
