### ISSUE TITLE
Mac - error 0.13.3

### ISSUE THREAD

**Issue by phree** [michaeldegroot/cats-blender-plugin#132]
On Mac 0.13.3 is giving an error in init.py on line 307 - "   tools.common.get_user_preferences().view.use_international_fonts = True"  - 

It is saying that the property " .view.use_international_fonts = True" does not exist. Now can't go back to the old CATS as I don't have 0.13.2 - ugh

**Comment by Darkblader24** [comment]
Please update to the latest cats and don't use the blender 2.80 beta anymore
