### ISSUE TITLE
QOL Suggestion: Backface Culling for 3d layout view should be enabled by default

### ISSUE THREAD

**Issue by Lhun** [michaeldegroot/cats-blender-plugin#133]
Small suggestion that makes sense for cats users, by default blender will use double sided normals visually, which will obscure issues with normal calculation after cat's "fix" operation is done. This is fine if you're creating pc models and using a shader with double sided normals, but it does have a performance hit: and for quest users, the default shaders do not allow for double sided mesh renderers. In fact, even unity's built in shaders require editing away from standard to get this functionality. 

I've found it's particularly common when bringing in self made sculpts from other software, it's not uncommon that normals will be flipped inappropriately - there are some ways to fix this but it can be tedious on lower poly meshes with layering. Low poly stranded hair made with nurbs for example. 

The setting can be found in the right side tool menu of the 3d view in blender 2.79 - I recommend toggling it on by default when cats is running.

**Comment by Darkblader24** [comment]
It is now on by default, thanks!
