### ISSUE TITLE
Kill mojibake: Shift-JIS and other languages, plus archive support

### ISSUE THREAD

**Issue by Lhun** [michaeldegroot/cats-blender-plugin#134]
Mojibake can cause issues with various scripts, when using japanese files. 
Inexperenced users can have issues extracting these files and it will cause issues with things like texture and material names as well as other scripts that can't handle things.
You guys handle a lot of translations really well, but if you added a zip/rar/7z etc option to the import model, you could prevent some of the issues new users tend to have and later blame on cats/unity/blender/vrchat when it is in fact a character encoding/paths issue. I've even seen some weirdness with texture formats getting broken in certain material/texture optimization steps like atlasing, where the missing texture or path element breaks the process when it's just directly unzipped without taking care to correct mojibake.
[This Git](https://github.com/RiceGnat/ShiftJisZipExtractor) has a c# implementation, I've seen a python one around too.

**Comment by Darkblader24** [comment]
Ok, I actually managed to get zips working! That was a lot of work, but it's a great improvement. Please give it a try in the development version of cats 👍

**Comment by Lhun** [comment]
That's wonderful! Did you implement the anti-mojibake portion I mentioned? I'll test it in just a moment. 
One other consideration that cause issues for some people: zipped mmd (and other) files will often have the "hidden" flag set on the texture references in the file, leading to texture-less models and repeat questions on discord and forums, (since blender can't find them). It would be useful to do a -h pass on the directory structure after unzip.

**Comment by Lhun** [comment]
oof. Without killing mojibake you may end up with some issues like this. The extraction needs to include shift-jis support. There's a simple solution, however, this binary as your unzip package: 
[Sjisunzip](https://github.com/kjerk/sjisunzip) should do the trick. 
It'll give you nice machine readable folders like picture related: 
![image](https://user-images.githubusercontent.com/23122906/65607303-4e0d2800-df7a-11e9-9d11-6f7983936324.png)



> 
> Traceback (most recent call last):
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\tools\importer.py", line 119, in execute
>     ImportAnyModel.extract_file()
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\tools\importer.py", line 246, in extract_file
>     ImportAnyModel.import_file(model_dir, model_file_name)
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\tools\importer.py", line 152, in import_file
>     log_level='WARNING')
>   File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy\ops.py", line 199, in __call__
>     ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
> RuntimeError: Error: Traceback (most recent call last):
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\extern_tools\mmd_tools_local\operators\fileio.py", line 163, in execute
>     self._do_execute(context)
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\extern_tools\mmd_tools_local\operators\fileio.py", line 195, in _do_execute
>     spa_blend_factor=self.spa_blend_factor,
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\extern_tools\mmd_tools_local\core\pmx\importer.py", line 768, in execute
>     self.__model = pmx.load(args['filepath'])
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\extern_tools\mmd_tools_local\core\pmx\__init__.py", line 1582, in load
>     with FileReadStream(path) as fs:
>   File "C:\Users\DylanBrown\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-development\extern_tools\mmd_tools_local\core\pmx\__init__.py", line 42, in __init__
>     self.__fin = open(path, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\\blender\\神宮寺レン\\É_ï{Ä¢âîâô\\FREECELLâîâô.pmx'
> 
> 
> 
> location: <unknown location>:-1

**Comment by Darkblader24** [comment]
Importing zips is now working, thanks for the suggestion!
