### ISSUE TITLE
I can't enable the addon i need help!

### ISSUE THREAD

**Issue by RealityJeez** [michaeldegroot/cats-blender-plugin#137]
Umm i need help with this error

**Comment by RealityJeez** [comment]
![Screenshot (174)](https://user-images.githubusercontent.com/52295524/60291722-c6346500-991b-11e9-81fc-71b01c221a4a.png)
Whenever I try to enable it this happens.

**Comment by Darkblader24** [comment]
Try reinstalling Blender.
Also did you set up Python as a system variable? If yes, try removing that.
