### ISSUE TITLE
Still can't use cats

### ISSUE THREAD

**Issue by Snipkitty** [michaeldegroot/cats-blender-plugin#138]
So, last time i posted on here i had issues with cats not enabling itself on blender. after trying all sorts of possible fixes, re downloading the plugin, and the developers version, uninstalling blender, i decided to try it again only to come back to it a couple months later. Instead i was given a new error that i took a screencap of below. Any idea what could be causing this? And yes, i have tried the development version as well, to no avail
![ghjf](https://user-images.githubusercontent.com/47465335/60782319-0bfee380-a0fb-11e9-9038-7fad332bfb7b.JPG)

**Comment by Darkblader24** [comment]
It's because for some reason you have the "mmd_tools_local" folder here: https://i.imgur.com/t3VwYh4.png
Just delete that and it should work

**Comment by Snipkitty** [comment]
Thank you. After deleting the folder everything works now.

**Comment by Darkblader24** [comment]
Great!
