### ISSUE TITLE
Cats Plugin 0.13.3 Installing with wrong Dir name

### ISSUE THREAD

**Issue by towneh** [michaeldegroot/cats-blender-plugin#139]
After installing the latest0.13.3 release from zip file, it creates a directory under:
\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons
called "cats-blender-plugin-0.13.3"
This prevents the plugin from appearing in the add-ons list.
To fix it, I had to manually rename the directory to "cats-blender-plugin-0-13-3"

**Comment by Darkblader24** [comment]
Ah yes, thanks for pointing that out, I added the correct zip to the release
