### ISSUE TITLE
Can't Import Model (2.8 - 0.13.3)

### ISSUE THREAD

**Issue by BlackbirdSong** [michaeldegroot/cats-blender-plugin#140]
Whenever I try I get this error.
![image](https://user-images.githubusercontent.com/12404597/61082562-b88cde00-a3f7-11e9-8ac9-0d088781d8c6.png)

**Comment by Darkblader24** [comment]
Are you using the latest cats version?

**Comment by BlackbirdSong** [comment]
Yes I am.

**Comment by Darkblader24** [comment]
But your folder structure is different from the one in version 0.13.3. Make sure that the correct one is enabled or uninstall all cats versions and then install only the latest one.

**Comment by BlackbirdSong** [comment]
I'll try to re-install again, does it need to be in the folder I open blender from(Not in C: drive)?

**Comment by BlackbirdSong** [comment]
Changing the save location of the add-on fixed it.

**Comment by BlackbirdSong** [comment]
Had to set the file path under user preferences.

**Comment by Darkblader24** [comment]
I see, glad you got it fixed
