### ISSUE TITLE
Join Mesh issue [Blender 2.8 ]

### ISSUE THREAD

**Issue by oivio** [michaeldegroot/cats-blender-plugin#141]
I did create rig with mixamo after importing the model and pressing button "Fix Model" Mesh did get 100 times smaller and outof the bones. When I do UnTick "Join Meshes" then it works as it should be. 
I can add that in Blender version 2.79 there is no problem. 
![28](https://user-images.githubusercontent.com/38628851/62235364-15632f00-b3cd-11e9-983e-8fa638ef724d.jpg)

**Comment by Darkblader24** [comment]
Is this the dev version of cats? If no, please try that out first, update with the build-im updater. If yes, please send me that fbx file

**Comment by oivio** [comment]
Oh, thank you. Dev version actually works. So fix is already there.

**Comment by Darkblader24** [comment]
Ok, glad to hear!
