### ISSUE TITLE
Import FBX from Daz3D 

### ISSUE THREAD

**Issue by oivio** [michaeldegroot/cats-blender-plugin#144]
It is nothing urgent but might be worth looking. I did just check that "Daz3D" feature  to see how it works. I did notice that after importing the model it looks wird. Even after "Fix Model" and switching from "Rest Position" to "Poste Position" we do get strage bone rotations. It is the same on Blende 2.79. It happen only when we have in import FBX option checkt "Use Pre/Post Rotation" If we uncheck that it will work just fine. Im not sure if it is good idea but maybe it might be good idea to add uncheck option  "Use Pre/Post Rotation" inside "Import Model"?
![28](https://user-images.githubusercontent.com/38628851/62276770-0e780300-b445-11e9-8402-f3ff72ac9393.jpg)

**Comment by Darkblader24** [comment]
Good idea, it's now in the dev version of cats
