### ISSUE TITLE
(Partial-)Support for Auto-Rig?

### ISSUE THREAD

**Issue by SuperFlue** [michaeldegroot/cats-blender-plugin#147]
Hi, I'm using Auto-Rig to help me rigging avatar models but basically almost all actions in CATS breaks the Auto-Rig tooling.

To some degree that is expected since Auto-Rig is using a lot of additional bones so full support here might difficult to implement.

So my current workflow is having a working model that i export as .fbx using Auto-Rig export function.
This strips away a lot of unnecessary bones and the export allows you to set up the model as ready for import in Unity (parenting the bones properly and stuff).
Then i open a new Blender project and import this model with CATS and do the final tweaks (like setting up eye tracking).

This workflow is not too bad to work with, but CATS is not able to automatically rename the bones so i have to do this manually.
Could support for automatically renaming Auto-Rig bones be added to CATS?

Off course i would like for CATS to fully support an Auto-Rig model but that might be expecting too much....

Here is a reference on how the bones are set up for a Auto-Rig model exported for Unity (with facial bones):
![image](https://user-images.githubusercontent.com/6199507/62834121-51f21e80-bc48-11e9-8b02-bbb522515783.png)

**Comment by Darkblader24** [comment]
I can add full support for those models, just send me an example

**Comment by SuperFlue** [comment]
Nice, thank you. :)
I am a bit reluctant to upload the model I'm working on and share it here since it is meant to be my private avatar. 
But i guess i can share the download link with you on Discord or something?

**Comment by Darkblader24** [comment]
Done 👍
