### ISSUE TITLE
Fix Model / Remove 0W Bones breaks on some models

### ISSUE THREAD

**Issue by Wunder-Wulfe** [michaeldegroot/cats-blender-plugin#149]
I've tried to use some of the CATS tools but they seem to not function properly on some rigs, not sure why.
All 3 of these appear to be bugged:
Fix Model, Remove 0 Weight Bones, Merge To Parent/Active.
Before:
https://i.gyazo.com/7c2ae58e014ccc436f33756b7b3e1eb3
After:
https://i.gyazo.com/db1ffe35d995c69e0bb9afdf658de09b

**Comment by Wunder-Wulfe** [comment]
there are no errors at all in console and if u would like 2 see the model I can send it PW locked

**Comment by Darkblader24** [comment]
Thanks for the report! This is caused by a visual bug in Blender 2.80 and I added a workaround in cats 0.15.0

**Comment by Wunder-Wulfe** [comment]
https://puu.sh/EkOxV/3a3aa32533.png
still appears to happen unfortunately, just upgraded CATS
https://puu.sh/EkOyU/d1ca4fb577.png
and there was some weird 'decoding the byte' or whatever error when i had Connect Bones turned on
