### ISSUE TITLE
Plugin installation failing

### ISSUE THREAD

**Issue by LabAviator** [michaeldegroot/cats-blender-plugin#15]
Hello.
My issue is that I cannot install this tool via the entire ZIP file into Blender. Neither does unzipping and putting it all into the Blender addons folder work. Either way the plugin does not show up under User preferences -> add-ons.

Possible solutions:

It should work with the newest Cat version following the installation instructions.
Optionally: Try using the Steam version of Blender.

**Comment by Darkblader24** [comment]
Mh, is there any error?

**Comment by alexhgian** [comment]
I'm also getting an install issue w/ a python error:
![image](https://user-images.githubusercontent.com/4159808/34460328-c495ab90-edbf-11e7-967c-645ebdb67280.png)

**Comment by alexhgian** [comment]
Okay, I some how resolved it after deleting a hidden temp file in
```
C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons
```

**Comment by wifininja** [comment]
I dont have a scripts folder in AppData Roaming folder, but I am still having the issue when I try to enable the addon

**Comment by RainBeee** [comment]
I have the same problem as alexhgian, but there's no hidden temp file in the addons folder

**Comment by wifininja** [comment]
I have seemed to solved the issue, I was installing it wrong. The install
via file should be used instead of just dropping the extracted file into
the addons folder. Let me know if that fixes the issue.

**Comment by RainBeee** [comment]
I solved it too by using the "Install Add-on from file" button and selecting the zip file instead of the files and folders inside of the unzipped folder.

**Comment by Siimmons** [comment]
Getting this error when trying to install

![](https://i.gyazo.com/1c03105dccf3fcb0d072a6ce36614647.png)

**Comment by LabAviator** [comment]
I myself do not get any kind of error message. Just the notification in Blender that it was supposedly installed (when it wasn't).

**Comment by Darkblader24** [comment]
@LabAviator Do you use the steam version of Blender?

**Comment by LabAviator** [comment]
No, I downloaded Blender directly from their website. Should I try the Steam version?

**Comment by Darkblader24** [comment]
No, don't do that. Go to the folder "%appdata%\Blender Foundation\Blender\2.79\scripts\addons" and show a screenshot of that folder please.

**Comment by LabAviator** [comment]
Well too late. I just tried the Steam version and the newest Cat version and it works now. I do not know if this is, because of a new Cat version or because of the Steam version of Blender.

**Comment by Darkblader24** [comment]
Well ok, if it works now it's good 👍

**Comment by michaeldegroot** [comment]
Closing this issue as it has been resolved
