### ISSUE TITLE
"Required Pillow"

### ISSUE THREAD

**Issue by Lexatiffy** [michaeldegroot/cats-blender-plugin#154]
Hello, I've been getting some strange crashes. When Cats required me to install some other plugin other than Material Combiner called Pillow it was finely installed, I restarted but. When I tried to generate the materials it keeps on crashing and crashing. And I'm not sure if I would even be able to see any logs of any crashes on 2.8.

**Comment by Darkblader24** [comment]
No, Blender has no crash logs unfortunately. But maybe try reinstalling Blender or installing Blender 2.79 to see if that fixes the crashes
