### ISSUE TITLE
Suggestion: Update CATs to not apply the FBT fix

### ISSUE THREAD

**Issue by ProbablePrime** [michaeldegroot/cats-blender-plugin#155]
As per: https://docs.vrchat.com/docs/full-body-tracking

CATs should be updated to not perform the full body fix as a part of its processing as this will eventually break avatars. the earlier this is removed from the fix step the better as less avatars will enter VRC in the old state which may break in subsequent updates to VRC

**Comment by Darkblader24** [comment]
I already removed it today in the dev version and I will publish an update soon
