### ISSUE TITLE
How to use the fix model feature without translating bone names?

### ISSUE THREAD

**Issue by 2dragons** [michaeldegroot/cats-blender-plugin#162]

**Comment by Darkblader24** [comment]
Thats not possible since the core point of Fix Model is renaming the bones and everything relies on it. Is there something specific from Fix Model that you want to do with your model?

**Comment by 2dragons** [comment]
Im trying to use a mmd model in a program that requres a fbx model with japanese bone names

**Comment by Darkblader24** [comment]
Why not just import that model and then immediately export it?

**Comment by 2dragons** [comment]
the textures are broken when i import the model

**Comment by Darkblader24** [comment]
Did you use japanese encoding when you extracted the zip? If you don't do this, texture file names will be garbled and Blender won't be able to find them

**Comment by 2dragons** [comment]
yes, the texture names are in japanese
