### ISSUE TITLE
ImportError when trying to enable

### ISSUE THREAD

**Issue by psiphre** [michaeldegroot/cats-blender-plugin#165]
[https://i.imgur.com/do6rOp2.png](url)

fresh install of blender 2.79, freshly updated python to 3.8.

**Comment by Darkblader24** [comment]
No, don't use python 3.8! Blender 2.79 comes with it's own Python which is 3.5 and it will only work with this version

**Comment by psiphre** [comment]
i will install python 3.5 and report back o7

**Comment by Darkblader24** [comment]
I assume it worked. If not, reopen this
