### ISSUE TITLE
i can't open cats

### ISSUE THREAD

**Issue by mafuyu97** [michaeldegroot/cats-blender-plugin#176]
![image](https://user-images.githubusercontent.com/61507473/75353439-fdf61100-58dd-11ea-9b22-d6786ee0e908.png)

**Comment by melvyn2** [comment]
Press `N` in the 3d viewport.

**Comment by negatron99** [comment]
Some of us don't use the Blender defaults, it's on the small context menu (the tiny "<" arrow in the top-right) on the right of the 3D window. For me in 2.81 "Industry Standard" layout "CTRL-]"
