### ISSUE TITLE
Separate MMD correct shading option

### ISSUE THREAD

**Issue by cherryleafroad** [michaeldegroot/cats-blender-plugin#179]
Could we have the correct shading option for MMD models as a separate button?

```
# Set correct mmd shading
mmd_root.use_toon_texture = False
mmd_root.use_sphere_texture = False
```

On one of my models, the Fix Model button breaks it, however I want to use the correct shading button

**Comment by Darkblader24** [comment]
If you look into the Misc tab, there are the MMD shading options: https://i.imgur.com/Bp7znN5.png
