### ISSUE TITLE
TODO: More flexible/correct VRM detection algorithm

### ISSUE THREAD

**Issue by usagi** [michaeldegroot/cats-blender-plugin#181]
I was happened this error in `Fix Model` feature with imported my VRM file:

![image](https://user-images.githubusercontent.com/115972/78840448-c11d4e00-7a35-11ea-96fe-01538dbcdcf8.png)

I think my VRM file is not broken then I read the source code about this error message.

- https://github.com/michaeldegroot/cats-blender-plugin/blob/5306d62014cbf9a99744e45dc94f6e858a62fdf2/tools/armature.py#L94

And, I found the `TODO` comment in the VRM detection algorithm:

```python
        is_vrm = False
        if len(Common.get_meshes_objects()) == 0:
            for mesh in Common.get_meshes_objects(mode=2):
                if mesh.name.endswith(('.baked', '.baked0')):
                    is_vrm = True  # TODO
            if not is_vrm:
                self.report({'ERROR'}, 'No mesh inside the armature found!')
                return {'CANCELLED'}
```

Maybe, this implementation is based on an undocumented `VRoid Studio` specific behavior. It is not VRM or Unity/humanoid or gltf specification. Thus, the author wrote `TODO` who implement the algorithm temporaly, maybe.

In now, we can use several tools for make a VRM format data. Some tools are output a VRM format file that has a different internal details to `VRoid Studio`. Therefore, I created this issue.

#### Reproducable example:

- <https://hub.vroid.com/characters/1537388192474504367/models/426275608358835909> ; The file is attached in the below:

[5383585797165228376.zip](https://github.com/michaeldegroot/cats-blender-plugin/files/4453230/5383585797165228376.zip)

It has no `.baked` or `.baked0` named meshes but it is a correct VRM format file for `VRoid Hub` at least.

![image](https://user-images.githubusercontent.com/115972/78842437-e791b800-7a3a-11ea-9eb5-7acec373527b.png)

-----

For reference, it is a mesh structure outputed by `VRoid Studio`. It has a `.baked` meshes.

![image](https://user-images.githubusercontent.com/115972/78842393-cfba3400-7a3a-11ea-9185-e62859d5bee5.png)

**Comment by Darkblader24** [comment]
Thanks for the report.
Unfortunately it's not possible to detect meshes from any VRM model. The .baked algorithm is just a quick fix solution. But instead I now have improved that error message to tell the user what to do. Also now when the user uses the cats import button to import vrm files, it will automatically reparent the added meshes to the armature without having to press Fix Model. (c434194933253dbe3f60a580413d6557c76aa705)
