### ISSUE TITLE
Can not check in 2.83

### ISSUE THREAD

**Issue by Eric8925** [michaeldegroot/cats-blender-plugin#185]
<img width="737" alt="Snipaste_2020-05-04_01-57-48" src="https://user-images.githubusercontent.com/57189172/80918917-b2af2180-8daa-11ea-9671-2ec5f03bbbda.png">

the error also occurs in 2.90

**Comment by Darkblader24** [comment]
Thanks for the report. This is already fixed in the development version of cats.
