### ISSUE TITLE
mmd_tools not installed

### ISSUE THREAD

**Issue by psycxtic** [michaeldegroot/cats-blender-plugin#20]
When i go on the cats tab in blender and click Import model it said the mmd_tool is not installed. I tried putting the extracted model in Program Files>Blender Foundation>Blender>2.79>scripts>addons. But it doesnt work. I tried restarting my pc also. Wont work also. 

If you know how to fix can you please tell me on discord: Psycxtic#2577

**Comment by Darkblader24** [comment]
This tutorial will show you how to install mmd_tools and how to use cats: https://www.youtube.com/watch?v=7P0ljQ6hU0A

**Comment by psycxtic** [comment]
thanks!
