### ISSUE TITLE
error pops up when i check the plugin box

### ISSUE THREAD

**Issue by dappertea** [michaeldegroot/cats-blender-plugin#21]
![image](https://user-images.githubusercontent.com/35200860/34653400-e14b106c-f3b0-11e7-9738-2b82a62a00d4.png)
full error is:
  File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\[user]\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\cats-blender-plugin-master\__init__.py", line 46, in <module>
    import tools.armature_bones
ImportError: No module named 'tools.armature_bones'
might just be a problem on my end, though reinstalling doesn't help

**Comment by whitelash2111** [comment]
I am getting the same issue, can't click check box give me error

**Comment by Darkblader24** [comment]
Hey, try to the latest Blender version 2.79 and see if the same error appears

**Comment by whitelash2111** [comment]
Hey Darkblader24, it did work to upgrade it to 2.79. For others, I am using Cat's blender .5
