### ISSUE TITLE
Please add an option to protect a list of bones from the Fix Model button

### ISSUE THREAD

**Issue by boomtnt46** [michaeldegroot/cats-blender-plugin#23]
It keeps deleting dome important bone I want to keep.
A button to select 1 or more bones to blacklist from the removil would be awesome.

Thanks for all your work!

**Comment by Darkblader24** [comment]
Uncheck the "Delete Zero Weight Bones" option. This should keep your bones from being deleted.

**Comment by boomtnt46** [comment]
But that option is right. It deletes a lot of useless bones. I want to keep a bone that actually does something but keeps being deleted.

**Comment by Darkblader24** [comment]
Does that bone have weight on it? And what is that bone called?

**Comment by boomtnt46** [comment]
The bones are called Breast1_L and Breast1_R. I don't think they have any weight because they are deleted.

**Comment by Darkblader24** [comment]
Before hitting Fix Model try to move those bones in pose mode and see if they actually move something.

**Comment by boomtnt46** [comment]
They don't move anything.

Is there are way to add the weight without using any external tool?

**Comment by Darkblader24** [comment]
Yes, this tutorial will help: https://www.youtube.com/watch?v=Tl4qTgwQwYw

**Comment by HartLeeKonnor** [comment]
Still one of the worst issues about this tool. Trying to add bunny ears to my model, and the bones have heavy weight as well as the tail, CATS dont care they just get deleted no matter what settings I try. This is ridiculous.
