### ISSUE TITLE
Combine material bug and fix

### ISSUE THREAD

**Issue by rich1051414** [michaeldegroot/cats-blender-plugin#24]
If a material does not have an image, the combine materials function fails. The fix is to check if the image exists before appending the hash value of it for unique material labeling.

https://github.com/michaeldegroot/cats-blender-plugin/blame/master/tools/material.py#L157

This works fine:
if hasattr(mtex_slot.texture, 'image') and bpy.data.materials[mat_slot.name].use_textures[tex_index] and mtex_slot.texture.image:

**Comment by michaeldegroot** [comment]
Thanks for your contribution, you could have sent me a pull request ;) but I included it into the code base.. seems to work fine!

**Comment by rich1051414** [comment]
I would have but the environment wasn't set up and I thought it was a waste of time to do all that for just a partial line fix :) Sorry if that was an inconvenience.
