### ISSUE TITLE
Decimate protect UV

### ISSUE THREAD

**Issue by felixjones** [michaeldegroot/cats-blender-plugin#27]
The current decimate implementation can be rather destructive to vertices with co-ordinates on UV edges. This is of particular issue to meshes that use mirroring for UV maps.

An option to preserve vertices with UVs on edges would be ideal for resolving this particular issue.

Blender's UV layout technique may be a good way of identifying what vertices have UVs that need preserving (UVs on edges).

**Comment by michaeldegroot** [comment]
Preserving UV detail is something i'm really keen in adding to the plugin. But automating this is really difficult to get it working and looking good. So far we are using the UV smart project feature of blender to generate uv mapping, this is trivial work. An ideal solution would be to have a native python module in c++/c# that can generate these mappings by figuring out seam marks, this would still require some user interaction but is by so far the best solution I could find 

There is a guy that started such project but sadly he never finished it: https://wiki.blender.org/index.php/User:Shuvro Check the heading: 'Automatic seam creation for UV unwrapping'

There might be a time when CATS can do this, but not in the near future.
