### ISSUE TITLE
cant enable the plugin with the new update

### ISSUE THREAD

**Issue by zxcold** [michaeldegroot/cats-blender-plugin#28]
i sadly cant enable the plugin with the new update and end up with this error,
![screenshot_4](https://user-images.githubusercontent.com/14300547/35313588-3a13ec88-008f-11e8-82ef-d9a1b31703c9.png)
i dont know the fix but i do think i caused it when i was reinstalling it after seeing an update.

**Comment by zxcold** [comment]
i managed to manually downgrade to 0.6 and enable the plugin, sadly the error seems to be with the new pose to shape button. for reference im using the latest version of blender from their site.

**Comment by Sagara42** [comment]
+1 have same problem too

**Comment by ButteredToast42** [comment]
I had the same issue but was able to resolve it by deleting blender's appdata folder and reinstalling the plugin.

**Comment by michaeldegroot** [comment]
if the solution of @ButteredToast42 does not help, please re-open this issue.. we are aware of the issue and see if we can fix this in the future, but for now.. unsure why this happens!
