### ISSUE TITLE
Cats blender error

### ISSUE THREAD

**Issue by EvaWinter404** [michaeldegroot/cats-blender-plugin#29]
Excuse me as you can see on these pictures, i did all the cats plugin and copied it into blender addons folder but when i was opened the blender (the blender was 2.70 version) it keeps saying an error like these.. 

![image](https://user-images.githubusercontent.com/36836562/36656983-441870f4-1afd-11e8-9711-e44f8887aa1a.png)

**Comment by Darkblader24** [comment]
Please use Blender 2.79 und try again.

**Comment by EvaWinter404** [comment]
okay...that problem is solved now and the new one was the FBX menu's in file>import FBX didn't showing
like this one
![image](https://user-images.githubusercontent.com/36836562/36773031-3fb2ee02-1c8a-11e8-9a47-4dba2e5e7e4b.png)

**Comment by Darkblader24** [comment]
As you solved this issue I will close this.
