### ISSUE TITLE
Mouth visemes not working in-game

### ISSUE THREAD

**Issue by Kushys** [michaeldegroot/cats-blender-plugin#30]
Issue: Shape keys work in Blender/Unity, but if put into the Avatar Descriptor in the appropriate location they simply do not work. The shape keys are fine if manually changed 0-100 in Blender and Unity. It's only when placed onto the Descriptor, they simply don't work in-game.

This is 100% a Blender and/or CATS plugin issue. It happened once before and reinstalling Blender/CATS fresh fixed it with no changes to my Unity or projects. Now it is broken again and my only hint is that both times it happened sometime after I stitched together a neck seam in my model in edit mode. I did not touch anything else on the model in the process - just merged vertices on the same location at the neck.

The weird thing is it happens on every model, so I can't chalk it up to editing my model being the problem, I think. Even if I bring in a brand new model and do the bare minimum (fix model + create visemes), it still will not work for me. I figured it must be something to do with the settings changing somehow due to how it persists across files and models.

**Edit: A few more things I've done to narrow it down now.**
On every step I make the changes, export the model, then upload it.
-Factory reset Blender settings, still broken.
-Then reactivated CATS plugin/mmd tools, recreated visemes, still broken.
-Deleted my Blender user folder in AppData (Only addons were mmd tools+ CATS). Still not working.
-Reinstalled mmd tools and CATS plugin (note: the 0.6.1 zip did not show up in my user preferences when trying to install, but the development one did so I'm now running development version unlike before.) Recreated visemes, still broken.
-Downgraded to 0.6.1. Recreated visemes, still not working

Sounds like it may just be a Blender issue somehow :(

Edit 2:
-Clean reinstall of Blender, still broken. I guess it ain't Blender but all my models suddenly :^)
**-Discovered this issue only affects CATS-created mouth movements** all other shape keys work in the Descriptor slots except for CATS ones. Even my own self-made shape keys work.

**Comment by Darkblader24** [comment]
If the mouth shape keys exist in Unity and they are working there then cats shouldn't be the problem. Maybe you use and old SDK version? Try to update that and see if it works.

**Comment by pierrce** [comment]
I had this issue as well and it seems to be something with how the VRCSDK overrides animations. If you replace walking/idle animations, the facial visemes won't work sometimes. I've submitted a ticket to VRChat asking for more information on this issue. If you haven't replaced any walking/idle animations I'm not sure what else the problem may be.

**Comment by Darkblader24** [comment]
Yes, this is probably the Vrchat issue @pierrce described. Because it doesn't make sense that they would work if you manually change them 0-100, but not Ingame. Reopen this if you have any more questions.

**Comment by Power2All** [comment]
I have the same issue now.
It worked fine before, but seems it ain't working anymore.

![image](https://user-images.githubusercontent.com/2010549/44106673-97bf2f68-9ff5-11e8-9810-e727f99eee6b.png)

![image](https://user-images.githubusercontent.com/2010549/44106696-a2b81538-9ff5-11e8-885f-ae9d7744493c.png)

**Comment by Grizdog** [comment]
I wonder if anyone ever found out what was causing this issue.  I'm having it now.
