### ISSUE TITLE
Texture issue

### ISSUE THREAD

**Issue by PSNsteven1230** [michaeldegroot/cats-blender-plugin#31]
Texture breaks when using the fix tool.
This is an FBX model. (not sure how to post the image so it shows.)
https://i.imgur.com/nWMCpSP.png

after hitting fix.

https://i.imgur.com/YAsBfze.png

**Comment by avail** [comment]
the uvmapping should still be fine, it just made it transparent for some reason. Try importing it into Unity and see if it's still OK?

**Comment by PSNsteven1230** [comment]
When I import into unity it only shows the jacket and shirt texture.  Which is an odd thing to have happen.

<img width="686" alt="2018-03-08_06h25_14" src="https://user-images.githubusercontent.com/9061063/37151089-cd97658a-2299-11e8-8687-7d6ec1d76264.png">


I had another avatar I did the same process with a few weeks back and it worked out just fine. So it is rather odd this one is causing so much issue.

**Comment by Darkblader24** [comment]
This is fixed in newer cats versions
