### ISSUE TITLE
Eye tracking problem?

### ISSUE THREAD

**Issue by ghost** [michaeldegroot/cats-blender-plugin#32]
Hi. Thank you for make and publish this plugin for all.
by the way, i got some terrible problem.

This is how I look my model in blender(after creating eye tracking) : [https://imgur.com/htAeJmi](https://imgur.com/htAeJmi)

What happened in unity : [https://imgur.com/qvbWe08](https://imgur.com/qvbWe08)

I changed Eye Movement Range very much. but it is almost in a dilemma.
I searched about for this problem everywhere, but I couldn't find a suitable solution.

I apologise for my foolishness :/

**Comment by Darkblader24** [comment]
I have no idea how this could happen, sorry
