### ISSUE TITLE
Full Body Tracking Fix 

### ISSUE THREAD

**Issue by SnowyChan** [michaeldegroot/cats-blender-plugin#41]
The full body tacking fix is detaching the bones from the mesh on a few of my models. When I unchecked the FBT fix box everything is fine. It detached the finger bones on one model and the other one it completely detached it.

**Comment by SnowyChan** [comment]
here's a pic
https://imgur.com/a/QOTlYcB

here's a link to the model, in case you wanna test it.
https://bowlroll.net/file/106876

**Comment by Darkblader24** [comment]
Oh that looks like a bone roll issue to me. Try setting the roll on your finger bones to 0. In the next update cats will do that automatically.
