### ISSUE TITLE
mergin armature

### ISSUE THREAD

**Issue by joekyu** [michaeldegroot/cats-blender-plugin#43]
so i moved the mesh o the place i wanted it and picked the stuff but when i cliked merge armatures it keeps saying please use the fix model feature even though i have used fix model on both armatures.

**Comment by Darkblader24** [comment]
Did you select the armature you want to fix in the box above the Fix Model button?

**Comment by joekyu** [comment]
oh i iddnt notice that i feel like an idiot now thanks for that! it worked now.
