### ISSUE TITLE
cats-plugin disappear and after i update the plugin,error occur

### ISSUE THREAD

**Issue by MikuNeeSama** [michaeldegroot/cats-blender-plugin#46]
hi, admin, I open my blender today and found out that cats plugin is gone then when I get to the user preference the plugin,its still on,then I go check the plugin webpage if any update,and there is update on MAY 2018 then I dl it and overwrite the plugin by following back the instruction given on the download page ,but then error occur when i try to activate it back,here is the reference picture,plesae help me ><><><
![cats plugin problem](https://user-images.githubusercontent.com/40124626/41194576-07f5db00-6c0d-11e8-9270-a7d6ecaa7df0.png)

**Comment by Darkblader24** [comment]
Try to start Blender as an admin

**Comment by Darkblader24** [comment]
I assume that this fixed it, reopen if it's not fixed.
