### ISSUE TITLE
Armature getting stuck in place because of cats

### ISSUE THREAD

**Issue by mcpedro99** [michaeldegroot/cats-blender-plugin#47]
Love the plugin, made life thousand times easier than the old days with mmd tools, no complaints about the plugin, just wanted to show what is happening with me and if this is a know issue. I preferred to record a video seeing it would be much easier to understand what is going on.

https://youtu.be/bvl73Z3mrco (just made the upload 7:51 pm est, might have to wait to process for better quality)

Both "tries" of moving the armature were exactly the same, seeing that I used "load factory settings" but after recording I realized that one difference was that the first try without cats, I opened a fbx and on the second with cats I used a mmd, so I decided to convert a mmd to fbx and move the armature without cats, no surprise, the armature moved normally, there might be a small chanca that the difference of models being in mmd are in fault here, but even so it need a fix, so I got to the conclusion that cats is to blame here, would love some support.

**Comment by Darkblader24** [comment]
It's because the transforms of the armature are locked: https://i.imgur.com/FXsvsoP.png
You can simply unlock them by clicking the lock icon.

**Comment by Darkblader24** [comment]
Press N to open that toolbar

**Comment by mcpedro99** [comment]
I'm confused now, how could cats lock the position out of nowhere? I reinstalled blender and cats twice, at this point I thought no config related to it would still be in the computer, so I would never think I was something simple like that. Wow so simple, Thanks a lot, but still wondering why everything would lock only when using cats.

**Comment by Darkblader24** [comment]
It's not cats doing it, it's mmd_tools, which comes automatically installed with cats. And it locks it because normally you don't want to move the armature if you are converting the model for vrchat.
