### ISSUE TITLE
pmx vs. Pmx Issue

### ISSUE THREAD

**Issue by OfficialOracle** [michaeldegroot/cats-blender-plugin#49]
Since the latest update today, on June 21, there has been an issue. My friend and I are able to Import pmx files. However, we are unable to import the files if the "P" in pmx is capital. This only started happening after I downloaded the update and re-launched Blender. Besides this, the update is great! Please fix asap, I am working on models that I need to be done soon! Thank you.

**Comment by Darkblader24** [comment]
Hey, thanks for the heads up!
It will be fixed soon, but for now either rename the .Pmx to .pmx or use the button next to the import button: https://i.imgur.com/psWXQxm.png

**Comment by Darkblader24** [comment]
I just fixed that issue.
So now you can also use the development version by updating to it with the build-in updater.
