### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DarkBlueLagoon** [michaeldegroot/cats-blender-plugin#50]
http://i66.tinypic.com/2uiccww.png

**Comment by DarkBlueLagoon** [comment]
or issue

**Comment by Darkblader24** [comment]
Try this:
- Go into the Addons in the User Preferences
- Search for "cats" and disable every version you can find
- Press Save User Settings
- Restart Blender
- Enable Cats and press Save User Settings again

It should work now
