### ISSUE TITLE
Lag every time whilst starting up Blender

### ISSUE THREAD

**Issue by makixx** [michaeldegroot/cats-blender-plugin#51]
Each individual image takes some time to load and it slows down Blender quite heavily. It might be better if you load only one image with all the supporters on there at once. Perhaps creating an automatic script to generate that image when pushing a commit. 

Here's a video that shows the issue:
https://streamable.com/b97b7

I think it's important because Blender aims to start up really quickly so you can just get on with your work. I swear I heard Ton say that in an interview and it's really annoying that this keeps happening.

**Comment by Darkblader24** [comment]
Thanks for the suggestion! That is indeed quite annoying.
I didn't know that you can load a single image file with all the icons on it. I will look into that.

Unfortunately I have exams soon so I won't have much time for the next month. Also this sounds pretty difficult to implement so it will take some time and I might not get it to work at all. But I will try!

**Comment by makixx** [comment]
I'll see if I can help figure something out as I've got some time. I'll report back if I do.

**Comment by Darkblader24** [comment]
Thanks, the help is very appreciated! 
I just made a quick Google search but couldn't find any info on this.

**Comment by priprii** [comment]
Are the images really necessary? They're too small to even make out what they are.

**Comment by makixx** [comment]
But Ton wanted Blender to be quick to start up and I think that's what make's it so awesome. Blender still has more features than cats, even tho I heavily appreciate the plugin. I've just been disabling the plugin when I don't need it.

I think I'm gonna make a clone of this repo on GItLab that updates automatically when this one does, and using continuous integration: automatically remove the icons and let it be auto update, download that instead.

**Comment by Darkblader24** [comment]
@makixx Sure, do that.
I assume you didn't find a solution either, so I will close this. Maybe 2.8 will have better ways to load images.

**Comment by makixx** [comment]
You could also just add a button which remembers you want to disable the supporters list...

Regardless, I made this for anyone who wants an easy fix for the time being: https://gitlab.com/makitsune/cats-blender-plugin-no-supporters#readme
