### ISSUE TITLE
Visemes not working from Blender to Unity

### ISSUE THREAD

**Issue by Power2All** [michaeldegroot/cats-blender-plugin#55]
Tried a lot as well.
Somehow the visemes aren't showing up, when they should.
Bug ?

https://user-images.githubusercontent.com/2010549/44106673-97bf2f68-9ff5-11e8-9810-e727f99eee6b.png

https://user-images.githubusercontent.com/2010549/44106696-a2b81538-9ff5-11e8-885f-ae9d7744493c.png

**Comment by Darkblader24** [comment]
Did you decimate after creating eye tracking and visemes? Are these shape keys emtpy in Blender? Can you send the that Blender save file so I can take a look at whats wrong?

**Comment by Darkblader24** [comment]
I see you managed to fix your problem in the Discord. I will close this now.
