### ISSUE TITLE
plans for Blender 2.8?

### ISSUE THREAD

**Issue by Lhun** [michaeldegroot/cats-blender-plugin#57]
My abusive relationship with blender might actually be at an end with 2.8, is there any hope for bugtesting and development to support the new version? 

I would be happy to contribute some time and effort into making this a reality.

**Comment by Darkblader24** [comment]
As soon as the API in Blender 2.8 will be stable, I will start working on making it compatible.
Bugtesting can be done by using the development version of CATS by selecting that version in the Updater panel.

**Comment by Lhun** [comment]
Thanks for the reply, I'll start on that soon. I've actually shoehorned it
into a nightly of 2.8.

**Comment by Lhun** [comment]
Changing the version on import just to get an idea of what is wrong, here's the current trace:
![2 8](https://user-images.githubusercontent.com/23122906/44555406-fbbc6080-a702-11e8-92cb-8c40f85f8c6b.PNG)

**Comment by Darkblader24** [comment]
There are still tabs, they appear as soon as CATS is enabled.
But I won't look in to making CATS compatible with 2.8 until the Blender API is final. Before that it is pretty much senseless to update any plugin, because it still can break at anytime again.

**Comment by arpu** [comment]
blender 2.8 is in beta

**Comment by arpu** [comment]
ah sorry i see developer branch should work with 2.8

**Comment by Darkblader24** [comment]
Happy to inform you that cats already works in 2.8. Only custom model creation and material merging doesn't work yet. 
You can test it out by using the development version of cats. If you encounter any issues, please report them.

**Comment by nulliel** [comment]
When I install cats I see it say "upgrade to 2.8x required". Is this expected until there's an official release for it?
