### ISSUE TITLE
Texture atlas fails

### ISSUE THREAD

**Issue by Murkur** [michaeldegroot/cats-blender-plugin#60]
trying to run a texture atlas on my model that was imported with cats but only end up with a traceback error as seen here (https://cdn.discordapp.com/attachments/487731343632105480/487762101205467137/Capture.PNG)

**Comment by Murkur** [comment]
now its failing to find the textures (just a node im doing this in the cycles render with Space engineer Havok texture nodes)

**Comment by Darkblader24** [comment]
Well cats needs to find the texture files. Are they stored differently with your method?

**Comment by Murkur** [comment]
the original texture files for the model were never released so you have to convert them from BC7 to BC4 compression for blender after that you load it into blender and the textures are loaded with another addon (space engineers block tools) so it loads these textures in a rather taboo way

**Comment by Darkblader24** [comment]
This doesn't sound like cats could support that. But you could try to create the texture atlas by searching for smart uv project in Blender. Maybe this works

**Comment by Murkur** [comment]
Alright ill keep digging but this is what I mean (https://cdn.discordapp.com/attachments/303428933209292800/487771870297325579/Capture.PNG)

**Comment by Murkur** [comment]
ok I got a somewhat update I removed the textures it was trying to find that dont exist but now its at another error (https://cdn.discordapp.com/attachments/303428933209292800/487773842782158849/Screenshot_25.png)

**Comment by Darkblader24** [comment]
"Permission Error, the device is not ready." Maybe try starting Blender as an admin.
Also this error occurs in the material combiner plugin, not in cats. Try to use the material combiner plugin directly and see if the error persists.
