### ISSUE TITLE
Cats Blender plugin Error

### ISSUE THREAD

**Issue by FallenAngel466** [michaeldegroot/cats-blender-plugin#61]
each time I have tried to enable the plugin from user preferences in the add-on tab, it would give me a report error. saying "AttributeError: module 'cats-blender-plugin-master' has no attribute '__file__'". there was more in it, but this was what stuck out to me. I will also add, when I first installed it, it worked fine, but after a change my region domain to Japanese and restarted my computer, it stopped working, I even tried reinstalling the cats plugin, nothing worked

**Comment by Darkblader24** [comment]
Please try again with the new update.

**Comment by Darkblader24** [comment]
I finally found out how to fix it:
- Go into the Addons in the User Preferences
- Search for "cats" and disable every version you can find
- Press Save User Settings
- Restart Blender
- Enable Cats and press Save User Settings again

It should work now
