### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Radizh** [michaeldegroot/cats-blender-plugin#69]
I came across this error when I tried to enable the addon.

![cats issue](https://user-images.githubusercontent.com/44451588/47467351-52e0cd80-d839-11e8-995f-3d45142ad6a3.PNG)

**Comment by joekyu** [comment]
i have the same problem, tried reinstalling blender and cats and both didnt work had the same problem.

**Comment by Darkblader24** [comment]
I finally found out how to fix it:
- Go into the Addons in the User Preferences
- Search for "cats" and disable every version you can find
- Press Save User Settings
- Restart Blender
- Enable Cats and press Save User Settings again

It should work now

**Comment by Lunasake** [comment]
It still isn't working for me

**Comment by Darkblader24** [comment]
It should work now in the latest development version of cats.
