### ISSUE TITLE
it wont let me tick it in addons

### ISSUE THREAD

**Issue by RavFromYetti01** [michaeldegroot/cats-blender-plugin#71]
I reinstalled the mod, didn't worked
I reinstalled Blender, still same issue.

https://i.imgur.com/FbT7XCT.png
https://i.imgur.com/y2VpKdy.png
https://i.imgur.com/p9Ar6lg.png

**Comment by Darkblader24** [comment]
Can you send me a screenshot of your addon folder?

**Comment by Darkblader24** [comment]
Ok here is how to fix it:
- Go into the Addons in the User Preferences
- Search for "cats" and disable every version you can find
- Press Save User Settings
- Restart Blender
- Enable Cats
It should work now
