### ISSUE TITLE
Blender Issues

### ISSUE THREAD

**Issue by spadeszeuxis** [michaeldegroot/cats-blender-plugin#76]
https://gyazo.com/26c7c19e4a02e174debf868aba1c742a

**Comment by Darkblader24** [comment]
You extracted the zip you downloaded. Don't do that! Go into your addons folder inside appdata and delete everything in there. Then install cats like this: https://camo.githubusercontent.com/6e8fb638b292d967316a3913d8156dd9081d7e49/68747470733a2f2f692e696d6775722e636f6d2f655a56317a72732e676966

**Comment by spadeszeuxis** [comment]
file keeps opening up with winrar rip

**Comment by spadeszeuxis** [comment]
https://gyazo.com/4a4117c1e915b2365c1e07104ce099da while doing this aswell i did what you said about deleting appdata aswell and didn't work, what i did hear was from the downloads was drag and drop it and import it but got the same message too

**Comment by Darkblader24** [comment]
Noo, don't delete appdata o.o delete only what is inside of the addons folder
If you really need to extract the zip, keep it all in a folder and paste that folder over into the addons folder

**Comment by spadeszeuxis** [comment]
https://gyazo.com/93ee9b1c68390321302a880fa835153a if i were to paste the folder all i would get is the setup

**Comment by Darkblader24** [comment]
You have to select the zip you downloaded there
