### ISSUE TITLE
Interface does not work, 12.1

### ISSUE THREAD

**Issue by Ziiro** [michaeldegroot/cats-blender-plugin#80]
![blender_2018-12-10_11-50-17](https://user-images.githubusercontent.com/26494679/49753847-cb78dd80-fc71-11e8-8fcb-e2824d3c4311.png)

Got an issue. I updated to the newest version using the built-in updater last night, and the "Model" dropdown doesn't have any options. Additionally, it appears that the autoupdater *itself* is busted. (Blender 2.79)

I've attempted to delete all traces of it and reinstall multiple times (I also removed mmd_tools, since it said it was built in now) but nothing I do seems to fix this. I notice your recent commits/changes attempted to change/fix it. Next step is going to be to nuke all of blender and try again.

**Comment by Darkblader24** [comment]
Yes, please test the latest development version. I added something that could fix the issues with 0.12
Update via the build-in updater to the development version or install it manually: https://github.com/michaeldegroot/cats-blender-plugin/archive/development.zip

**Comment by Darkblader24** [comment]
Try I the dev version again. I will work now.

**Comment by Ziiro** [comment]
![blender_2018-12-15_10-38-19](https://user-images.githubusercontent.com/26494679/50045740-94317480-0055-11e9-9c18-db3bda84b6bc.png)

Yep, all fixed.
