### ISSUE TITLE
 ats disappeared from Blender

### ISSUE THREAD

**Issue by Patovirtual** [michaeldegroot/cats-blender-plugin#81]
Cats disappeared from the Steam Blender layout, and it is displaying the following error when I disable it and try to enable it again.
![catsbug](https://user-images.githubusercontent.com/35778550/50049432-f4afc880-00cc-11e9-864f-0f3663f48b2c.png)
![cats](https://user-images.githubusercontent.com/35778550/50049434-f8dbe600-00cc-11e9-85e8-678fff9044e9.png)
![cats2](https://user-images.githubusercontent.com/35778550/50049435-fb3e4000-00cc-11e9-9c50-20e17e938835.png)

**Comment by Darkblader24** [comment]
Install the development version, it should be fixed there
