### ISSUE TITLE
Found an issue trying to activate it

### ISSUE THREAD

**Issue by ThatOnePixelNerd** [michaeldegroot/cats-blender-plugin#83]
![screen shot 2018-12-19 at 5 21 57 pm](https://user-images.githubusercontent.com/46009583/50251891-3e413180-03b3-11e9-8754-a3dfdc802886.png)

**Comment by Darkblader24** [comment]
Please try installing the development version of Cats: https://github.com/michaeldegroot/cats-blender-plugin/archive/development.zip
