### ISSUE TITLE
Feature Request (Enhancement): Resize parent bones when Merging Weights To Parent

### ISSUE THREAD

**Issue by whitebyakko** [michaeldegroot/cats-blender-plugin#85]
While using the merge weights (to parents) feature under Model Options I noticed that the parent bone doesn't resize itself to make up for the deleted bone. For example, if you had a chain of 3 bones (each one parented and connected to another) and you use the merge weights feature to merge the middle bone with its parent there will be a gap between the parent bone of the selected and the child bone of the selected.
Crappy Illustration:
Starting______ : [---A Bone----][---B Bone----][---C Bone----]
After Merge__: [---A Bone----]-----Gap-------[---C Bone----]
Expected_____: [---A Bone--------------------][---C Bone----]
More detailed illustration:
Result:
 ![result](https://user-images.githubusercontent.com/46077261/50379744-cc215480-061f-11e9-917b-0b07f48edc44.PNG)
Expected:
![expected](https://user-images.githubusercontent.com/46077261/50379745-ce83ae80-061f-11e9-9423-1cadc927db59.PNG)
 To me this doesn't look very nice and fixing it can be tedious when you are doing this to dozens of bones. From what I've found out you can fix this by selecting the chain, flipping the bone directions, connecting all the bones, and flipping the bones back. This method is much better then my original method (manually resizing all the bones) but the resulting bone chain will be unparented from its former parent. So what I'm proposing is in the script for Merge Weight (To parent) before deleting the selected bones change the parent bone's tail transform to be the tail transform of the selected bone. 

To me this seem like it would be useful for reducing a lot of bone chains, such as for hair, skirts, strings, etc in the armature, however there are cases where this would not help. For example merge weight (to active) would probably be used to merge bones that do not share a common parent, in this case it is likely that this feature would resize the bone when it shouldn't. Another example would be when a parent bone has multiple children, in this case resizing the parent bone to fit one of it children will make the other children looks weird (like if a wrist bone was connect to only one finger all the other finger bones would look out of place). This second issue can be resolved by adding a checker to see if the parent bone has multiple children. 

Well that's the enhancement I'm proposing, please consider it for future releases. 
If you have any question you can reach my discord at @ White Byakko in the CAT discord

**Comment by Darkblader24** [comment]
Thanks for the suggestion and sorry for the late reply.
I have considered this as well, but in my testing this sometimes resulted in huge bones covering large parts of the model. That's why I didn't add this.
But I could add this as an option in the cats settings.
