### ISSUE TITLE
cats wont install

### ISSUE THREAD

**Issue by ky007** [michaeldegroot/cats-blender-plugin#86]
![capture](https://user-images.githubusercontent.com/46096081/50389249-03623500-06f6-11e9-8d83-c78d95541407.PNG)
I cant seem to get the cats tool to install any more. I've been using cats for almost a year so its not my first time. but all I get is this error on the captured image. please help.

**Comment by Darkblader24** [comment]
Try installing the development version: https://github.com/michaeldegroot/cats-blender-plugin/archive/master.zip

**Comment by ky007** [comment]
it still gives me the same error.

**Comment by Darkblader24** [comment]
You didn't uninstall the old version then. Uninstall all cats versions, save user settings then install dev version

**Comment by ky007** [comment]
just so I know Im doing it right, I go into user preferences/ search for cats in the search bar and under cats blender plugin click remove, then save user settings, close blender, reopen blender and go back to user preferences  go to install addon, look for the zip file you sent me and hit install addon from file, check the box next to the new version of cats and click save settings.

**Comment by Darkblader24** [comment]
Exactly, that should work

**Comment by ky007** [comment]
it didn't.

**Comment by ky007** [comment]
it was working earlier today but there was an update for it so I updated it and it worked fine during that project but when I went to do another project it was gone

**Comment by ky007** [comment]
I fixed it. I ended up deleting all things blender related after uninstalling it

**Comment by Darkblader24** [comment]
Good, I will close this then
