### ISSUE TITLE
Error while installing addon

### ISSUE THREAD

**Issue by blenderkilledmycat** [michaeldegroot/cats-blender-plugin#87]
![blendererror](https://user-images.githubusercontent.com/46096249/50408301-c9ed0080-07ad-11e9-9d56-46979616f22b.png)
I have removed the Cats addon from blender then re-downloaded and tried to install from blender and have gotten the same code every time.

**Comment by Lhun** [comment]
I have written a fix for this that allows the plugin to install in the sidebar, I'll do a pull request.

**Comment by Darkblader24** [comment]
@blenderkilledmycat Please try installing the development version of Cats: https://github.com/michaeldegroot/cats-blender-plugin/archive/development.zip
