### ISSUE TITLE
Fails to enable due to context not having user_preferences.

### ISSUE THREAD

**Issue by Alexia** [michaeldegroot/cats-blender-plugin#88]
Blender 2.8 built on 2018-12-22.  After installing the plugin fails when attempting to enable it.  Commenting out the two lines that sets user preferences bypasses the issue and allows the plugin to load.

![screenshot 401](https://user-images.githubusercontent.com/248632/50411802-b307d780-07c8-11e9-8af4-e60daf37bd38.png)

**Comment by Darkblader24** [comment]
Oh they might have removed or renamed that option. Thanks for reporting, I will fix this

**Comment by Mahagon** [comment]
> RNA: naming, user-preferences -> preferences

https://developer.blender.org/rB63fcbfc3a7325d79b9e916457d64c302ddfeadfa

**Comment by Darkblader24** [comment]
Thanks, it's fixed now and I fixed another 2.8 bug that I found along the way.
