### ISSUE TITLE
Error on Export Model

### ISSUE THREAD

**Issue by Controser** [michaeldegroot/cats-blender-plugin#91]
When I tried to export my model in Blender to FBX through cats I ran into this error posted below. The only thing I have done differently is applied textures and materials to model parts that did not have them before and just showed up as pink. Was not having this issue prior but cannot reverse what I have done now. Anyone know how to fix this?

Traceback (most recent call last):
File "...\Blender\2.79\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 573, execute
tex_path = bpy.path.abspath(text_slot.texture.image.filepath)
AttributeError: 'NoneType' object has no attribute 'filepath'

Location: <unknown location>:-1

**Comment by Darkblader24** [comment]
This is now fixed in the latest development version of cats.
