### ISSUE TITLE
Cant enable addon and tried everything that i could think of

### ISSUE THREAD

**Issue by spacewitchdog** [michaeldegroot/cats-blender-plugin#94]
![image](https://user-images.githubusercontent.com/46512282/50876127-2f85e300-1391-11e9-992d-8ea693ea60a0.png)
 It says to restart blender and then enable CATS, but I've done it a thousand times as well at trying to uninstall blender and do it again, and restarting my computer but that seemed to do nothing, not sure what to do here because I've tried the "Go into the Addons in the User Preferences Search for "cats" and disable every version you can find, Press Save User Settings Restart Blender Enable Cats and press Save User Settings again." but that wont work either.

**Comment by Darkblader24** [comment]
It does this when it could not find the settings file in the cats folder. Try using the cats updater in the user preferences to reinstall the latest cats version. You can find that in the drop-down menu in the addon list

**Comment by spacewitchdog** [comment]
When you mean finding the cats updater in the user preferences, do you mean by going to the addons tab and look up cats updater in the search bar or am i missing something here?
if that's what you mean then there is no "cats updater" in the addons

**Comment by Darkblader24** [comment]
I mean this: https://i.imgur.com/xiIirB8.png

**Comment by spacewitchdog** [comment]
![image](https://user-images.githubusercontent.com/46512282/50935837-09188400-1433-11e9-9aa7-1ded160116c5.png)
?

**Comment by Darkblader24** [comment]
Enable cats and then click that error away

**Comment by spacewitchdog** [comment]
thing is, i cant enable it because it either says the "please restart blender and enable CATS" or that its already registered as a subclass?

**Comment by spacewitchdog** [comment]
![image](https://user-images.githubusercontent.com/46512282/51003379-1b122980-14fc-11e9-8637-f8840910383f.png)
This is what appears After i try to enable it the first time

**Comment by Darkblader24** [comment]
I think this should be fixed now, please test again with the latest development version of cats. Reopen this if these errors still occur.
