### ISSUE TITLE
Will not load on Blender 2.80 on Mac

### ISSUE THREAD

**Issue by UiharuKazari2008** [michaeldegroot/cats-blender-plugin#95]
I am trying to load the add-on for Blender 2.8 running on Mac but I'm getting a error about using international fonts
![screen shot 2019-01-09 at 01 47 21](https://user-images.githubusercontent.com/15165770/50881807-c1511880-13b0-11e9-895f-78cb772245a0.png)

**Comment by Darkblader24** [comment]
Oh, they probably renamed that recently. I will fix this soon.

**Comment by Darkblader24** [comment]
It's fixed in the development version of cats, use the updater to update.
