### ISSUE TITLE
Blender Crashing When Minimized

### ISSUE THREAD

**Issue by Zerothoughts6** [michaeldegroot/cats-blender-plugin#96]
Blender has been successfully installed on my computer and it opens perfectly. But if I minimize Blender or click on an external program and click back in Blender crashes every time. I have tried different versions of blender with no luck. I also made sure that I had the current version of windows and gpu drivers. 

Any help would be much appreciated! I have also found that I am not the only one experiencing this.

**Comment by Darkblader24** [comment]
Sorry, I can't help you with Blender issues if they aren't cats related. You should report this as an official blender Bug
