### ISSUE TITLE
Cant enable addon 

### ISSUE THREAD

**Issue by SanokKule** [michaeldegroot/cats-blender-plugin#99]
![image](https://user-images.githubusercontent.com/24497821/51229348-7c5f5000-1975-11e9-8b71-cd3d4e03d1f4.png)

**Comment by Darkblader24** [comment]
Update cats to the development version with the updater. It's fixed there

**Comment by MarioKart7z** [comment]
But how am i supposed to use the updater if i can't install the add-on at all?

**Comment by Darkblader24** [comment]
In the addon list in the preferences there is an arrow next to the cats plugin. You can find the updater there

**Comment by ProbablePrime** [comment]
I manually downloaded the development edition and this error still occurs here.

**Comment by MarioKart7z** [comment]
> 
> 
> I manually downloaded the development edition and this error still occurs here.

Same here

**Comment by ProbablePrime** [comment]
Interesting, looks like it loads but those errors occur.

**Comment by smirgol** [comment]
Had the same issue, restarting blender after installing addon did fix it. The updater is not available until you've activated the plugin btw.

**Comment by Darkblader24** [comment]
I will close this now as this should now be fixed in the latest developmet version. But if those errors still occur with there, please reopen this.
